### ISSUE TITLE
Bring Mongoose library into project.

### ISSUE THREAD

**Issue by evscott** [reisman-internship-2019-greenmap/GreenMap-server#17]
So that the server can query a MongoDB, the library Mongoose needs to be brought into the application. It should only be implemented in the project's controller file.

How this should be done is:

- Bring the Mongoose library into the project.
- Create a controller function which makes a query to a MongoDB using Mongoose. The query can be whatever is best for testing purposes right now - we will be provided with a valid query from the database team soon.
- Return the result of a query as a response to the caller with corresponding response status code.

**Comment by ShekharDewan** [comment]
Check this out. Mac has made substantial progress on the MongoDB server. Might be good to put heads together either tomorrow or Thursday. 

https://github.com/reisman-internship-2019-greenmap/GreenMap-Database/tree/%237-MongoDB

**Comment by nimeshnayaju** [comment]
If I am not mistaken, this would first require creating a [Schema](https://mongoosejs.com/docs/guide.html) after connecting to the mongodb database. Then, we could make query via the Schema model.
